# Generated by Django 3.2.3 on 2021-05-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_card_categorie_categoriework_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.FileField(default=1, upload_to='image_card'),
            preserve_default=False,
        ),
    ]
