# Generated by Django 3.2.3 on 2021-05-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20210524_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='sous_titre',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='image',
            field=models.FileField(default=2, upload_to='image_work'),
            preserve_default=False,
        ),
    ]
