# Generated by Django 3.2.3 on 2021-05-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20210524_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerwork',
            name='Image',
            field=models.FileField(default=1, upload_to='banner_work_image'),
            preserve_default=False,
        ),
    ]
