# Generated by Django 3.2.3 on 2021-05-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_work_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='categorie',
        ),
        migrations.AddField(
            model_name='work',
            name='categorie_test',
            field=models.ManyToManyField(related_name='work_categorie', to='service.CategorieWork'),
        ),
    ]
