# Generated by Django 3.2.3 on 2021-05-27 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_auto_20210527_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='categorie_test',
        ),
        migrations.AddField(
            model_name='work',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='work_categorie', to='service.categoriework'),
            preserve_default=False,
        ),
    ]
