# Generated by Django 3.2.3 on 2021-05-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_auto_20210527_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='icone',
            field=models.CharField(max_length=200),
        ),
    ]
