# Generated by Django 3.2.3 on 2021-05-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_alter_pack_icone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='prix',
            field=models.IntegerField(),
        ),
    ]
