# Generated by Django 3.2.3 on 2021-05-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_alter_pack_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='periode',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
