# Generated by Django 3.2.3 on 2021-05-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitewebapp', '0003_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('image', models.FileField(upload_to='image_choice')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'AboutChoice',
                'verbose_name_plural': 'AboutChoice',
            },
        ),
    ]
