# Generated by Django 3.2.3 on 2021-05-26 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitewebapp', '0004_aboutchoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerhome',
            name='description_2',
        ),
        migrations.RemoveField(
            model_name='bannerhome',
            name='description_3',
        ),
        migrations.RemoveField(
            model_name='bannerhome',
            name='titre_2',
        ),
        migrations.RemoveField(
            model_name='bannerhome',
            name='titre_3',
        ),
    ]
