# Generated by Django 3.2.3 on 2021-05-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitewebapp', '0006_icone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReseauSociaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('nom', models.CharField(max_length=200)),
                ('icone', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'ReseauSocial',
                'verbose_name_plural': 'ReseauSociaux',
            },
        ),
    ]
