# Generated by Django 3.2.3 on 2021-05-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitewebapp', '0008_alter_about_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.FileField(upload_to='')),
                ('nom', models.CharField(max_length=200)),
                ('job', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
    ]
