# Generated by Django 3.2.3 on 2021-05-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitewebapp', '0009_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='description',
        ),
        migrations.RemoveField(
            model_name='team',
            name='titre',
        ),
        migrations.AddField(
            model_name='website',
            name='description_team',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website',
            name='titre_team',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
