# Generated by Django 3.2.3 on 2021-05-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitewebapp', '0011_alter_team_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='progres',
            field=models.IntegerField(),
        ),
    ]
